### ISSUE TITLE
请问您后续还有继续研究这个Strapi吗

### ISSUE THREAD

**Issue by bluehr** [AutumnFish/strapi_study#1]

**Comment by AutumnFish** [comment]
hello，你好
&nbsp; &nbsp;strapi之后用继续使用，并且这个完成一个项目的中台编写，不过由于工作的原因没有继续维护这个文档了
&nbsp; &nbsp;请问有什么使用上的问题吗，没准可以帮得到你哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AutumnFish/strapi_study"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月5日(星期五) 下午2:21
收件人:&nbsp;"AutumnFish/strapi_study"<strapi_study@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[AutumnFish/strapi_study] 请问您后续还有继续研究这个Strapi吗 (#1)

**Comment by bluehr** [comment]
> hello，你好 &nbsp; &nbsp;strapi之后用继续使用，并且这个完成一个项目的中台编写，不过由于工作的原因没有继续维护这个文档了 &nbsp; &nbsp;请问有什么使用上的问题吗，没准可以帮得到你哈
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "AutumnFish/strapi_study" <notifications@github.com&gt;; 发送时间:&nbsp;2021年2月5日(星期五) 下午2:21 收件人:&nbsp;"AutumnFish/strapi_study"<strapi_study@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[AutumnFish/strapi_study] 请问您后续还有继续研究这个Strapi吗 (#1) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

确实是有一个使用上的问题，我现在想用这个Strapi 去做后端api生成配合前端低代码平台 

**目前有些需求不满足，我想自定义响应内容，或者修改某个api。**
看官方文档的意思，是让我自己去某个想修改的api的controller中覆盖这个方法。那这样有个问题是，我想所有的方法都修改为这样的响应体，请问您知道怎么搞吗？ 还望指教

**Comment by AutumnFish** [comment]
可以使用中间件的方式来解决，在中间件中统一处理响应哈
https://strapi.io/documentation/developer-docs/latest/concepts/middlewares.html#structure
你可以看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AutumnFish/strapi_study"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月5日(星期五) 下午5:44
收件人:&nbsp;"AutumnFish/strapi_study"<strapi_study@noreply.github.com&gt;;
抄送:&nbsp;"时间煮鱼`"<517729329@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [AutumnFish/strapi_study] 请问您后续还有继续研究这个Strapi吗 (#1)





  
hello，你好 &nbsp; &nbsp;strapi之后用继续使用，并且这个完成一个项目的中台编写，不过由于工作的原因没有继续维护这个文档了 &nbsp; &nbsp;请问有什么使用上的问题吗，没准可以帮得到你哈
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "AutumnFish/strapi_study" <notifications@github.com&gt;; 发送时间:&nbsp;2021年2月5日(星期五) 下午2:21 收件人:&nbsp;"AutumnFish/strapi_study"<strapi_study@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[AutumnFish/strapi_study] 请问您后续还有继续研究这个Strapi吗 (#1) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
确实是有一个使用上的问题，我现在想用这个Strapi 去做后端api生成配合前端低代码平台
 
目前有些需求不满足，我想自定义响应内容，或者修改某个api。
 看官方文档的意思，是让我自己去某个想修改的api的controller中覆盖这个方法。那这样有个问题是，我想所有的方法都修改为这样的响应体，请问您知道怎么搞吗？ 还望指教
